### PR TITLE
Add TOP3 - Vertical

### PR DESCRIPTION
**Pull request by jbdwi**

### CODE REVIEW

**Comment by jbdwi** [comment]
Added to  TO_SOT_Packages_THT.pretty - footprint of transistor package TOP3. Related files : *.kicad_mod, *.wings, *wrl.
- TOP3_Hor_Sub : Horizontal Sub ( below the board ). 
  top3_v1_hor_sub
- TOP3_Hor_Sup : Horisontal Sup ( above the board) 
  top3_v1_hor_sup
- TOP3_Ver : Vertical 
  top3_v1_ver

**Comment by CarlPoirier** [comment]
Hi Josef,

Your pull request is perfect. The only things now that needs reworking are your footprints. We have a set of rules ( https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention ) that you need to follow when designing them. For example, in the footprints you added, you don't have a courtyard and the parts aren't centered around pad one.

We don't have such set of rules for 3D models. As long as they follow the manufacturer dimensions and look good, they will be accepted. That's why it's much easier to contribute 3D models to existing footprints than to add both.

**Comment by jbdwi** [comment]
Hi Carl,
Thanks for the response.

Well, for footprint editing I ve been learning about the KLC, and of course learning the official Kicad libraries. 

1).
A little bit confuse about : pad-one centered and courtyard. As I found in the lib, some component follow the KLC rule, some component not, as in this screenshot. The Elco follows the KLC by centering around pad 1, but the Buzzer doesn't. 

image

2) 
Also regarding the courtyard. I met some component has a courtyard but some component has not a courtyard. Or I did misunderstand about what a courtyard is. 

image

3).
As with the footprint I put, forexample the TOP3_Ver above, I assumed that those f/p has a couryard ( which in my mind, which could be incorrect, an area which is another component can not be placed there ). Or any specific feature or setting to add a courtyard in a footprint ? Pls advise.

image

4). quote " That's why it's much easier to contribute 3D models to existing footprints than to add both. "
Carl, I love to do it. But the detail dimension document did not always available. Almost all the 3dmodels I sent here, are the model which I used in my past or recent project with 1st generation of KiCad. So for this recent time, I just put what I have had in my library.

I have an idea, for completing the 3dmodels to some f/p which has not one, pls. you or another librarian or another contributor just send me the detail specs of a component. And I will model its 3d and send it to you , the admin to add it to its footprint. I have about 1 or 2 hous sparetime a day to do this volunteer task ( FYI, one of my hobby is sketching and drawing of anything ). I think such a collaboration will speed up the jobs ).

Well, thanks again for yr attention. Hope I can more better understanding the way how to contribute in correct way to this amazing KiCad Project.

Cheers, JBD.

**Comment by CarlPoirier** [comment]
Hi Josef,

Not all footprints in the libraries are compliant to the KLC. The latter is relatively recent are we are not done updating the existing footprints. That's another area where we need more manpower. Thus, take example on the ones that are compliant.

As for 3), your are right in your understanding of the courtyard. However, make sure to differentiate between footprint outline, placed on silkscreen, and courtyard, placed on courtyard. ;-)

For your TOP3-model1-sub, I suggest you remove the silkscreen rectangle encasing the pads, as it has no real contribution to the footprint. The remaining is the outline which shows exactly where the part needs to be. Then, just draw the courtyard as one big rectangle containing everything, which has a 0.25mm spacing from the part, rounded to the 0.05mm. These are rules 6 and 7 in the KLC.

Lastly, there are some python scripts which you can use to validate your footprint for many of the KLC rules. Are you familiar with running python scripts?

Now for 4). I will look into generating a list of all the components that miss their 3D model. Then you will only have to get the datasheet from the web and draw it. How does that sound?

I hope this helps.

**Comment by jbdwi** [comment]
Hi Carl,

1).
Regarding c/y :  is this correct as what you said ?
image

2).
// Quote : "However, make sure to differentiate between footprint outline, placed on silkscreen, and courtyard, placed on courtyard. ;-) "
Honestly I didnt know how to do it ... how to differentiate those two layer. Pls advice.

3). About python. 
Nope, just familiar with solder, C and assembler. Anyway, it is the good time to start learning python.

4). Well, that sounds great. Done !

**Comment by michal777** [comment]
It's quite hard to find footprints that are 100% good (in terms of the convention).

About courtyard and silkscreen: Multiwatt_15_Horizontal and Multiwatt_15_Vertical are good examples - the silkscreen (blue lines on F.SilkS) will be printed on pcb (it's simplified drawing of the component and it omits pads), the courtyard (gray lines on F.CrtYd) won't be printed - they helps while designing (it outlines the component with pads to ensure that components won't overlap) - courtyard (gray 0.05mm enlarged outlines) in action:
zrzut ekranu z 2015-09-30 20 55 51

**Comment by jbdwi** [comment]
Hi Michal,
Thanks  for the explanation.

**Comment by jbdwi** [comment]
Carl n Michal,
Regarding the courtyard, with example of TOP3_Model1_Sub above, in my project so far, mostly it was implemented as in Fig 1. So, the courtyard was around the pads.

However, sometimes it was implemented as in Fig 2. In this case, sometimes I put component in the area X. So, in this case, according to KLC how I have to define the courtyard ? Pls. advice !

image

**Comment by CarlPoirier** [comment]
For Fig. 1), it's great for the top side. For the bottom, just enlarge your
courtyard (if it is that yellow dashed rectangle) to include the pads as
well. Also, there is no need to circle the mounting hole as it should be
included as well in the courtyard.

About the python scripts, I will add some more information in the wiki so
everyone will be able to read it.

**Pull request closed without merging**
