### PR TITLE
added TO-3PB & TO-220-5 (straight)

### PR DESCRIPTION
**Pull request by jkriege2**
- see: http://pl-1.org/getproductfile.axd?productid=9495&filename=IRF260.pdf
- script-generated: https://github.com/pointhi/kicad-footprint-generator/pull/27

2017-02-19 11_16_40-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb
2017-02-19 11_54_41-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 the pitch seems to be a little off? Datasheet says pitch is 5.45mm but you have the pitch at 5.47? Is there a reason for this?

**Comment by jkriege2** [comment]
good spot: should be fixed now!
thanks,
JAN

**Comment by jkriege2** [comment]
PS: I'm reworking the different footprint-links in the symbol-libs ... and needed also the TO-220-5, so for convenience I added it here too ... if I need further footprints, I'll open a new branch, since you're already reviewing ;-)

**Comment by SchrodingersGat** [comment]
Thanks for fixing :)

**Pull request merged**
