### PR TITLE
add TO-99

### PR DESCRIPTION
**Pull request by jonasstein**
http://www.jedec.org/sites/default/files/docs/archive/to/to-099.pdf

### CODE REVIEW

**Comment by pointhi** [comment]
Please fix [KLC](https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt):

```
checking module: TO-99
  Violating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
  Violating Rule 6.9
    Value and reference have a height of 1mm.
```

also note, you could use circle holes instead of oval ones

**Comment by jonasstein** [comment]
Thank you for the review.
6.3 was easy to solve, but I have difficulties with Rule 10.2
    Doc property contains a full description of footprint.
What besides TO-99 goes here?

could you link to a good example I can learn from?

**Comment by pointhi** [comment]
> What besides TO-99 goes here?

When the component is something generic like your one, not much :) Simply look what other TO footprints write.

When you have more specific footprints like connectors, normaly you use the datasheet url.
This would also be valid in your case because your datasheet is more or less a generic one.

**Comment by jkriege2** [comment]
this is also part of this PR: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14

**Comment by jkriege2** [comment]
This is fixed this this PR: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14

best,
JAN

**Pull request closed without merging**
