### PR TITLE
reworked all TO-92 to conform to KLC + added TO-92 footprints with only 2 pins each

### PR DESCRIPTION
**Pull request by jkriege2**
- added 2-pin TO-92 packages
- I modified all TO-92 to conform to KLC now (added Fab, improved CrtYrd, ...)
- added 3d packages, see this pull request for the 3d models: https://github.com/KiCad/kicad-library/pull/715
- see #14 for fixes of most of the other packages (T220...)!

2016-12-25 17_31_03-footprinteditor keine aktive bibliothek

2016-12-25 17_30_24-footprinteditor keine aktive bibliothek

2016-12-25 17_38_39-3d betrachter

2016-12-25 17_39_20-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb

### CODE REVIEW

**Comment by jkriege2** [comment]
added 3d packages, see this pull request for the 3d models: https://github.com/KiCad/kicad-library/pull/705https://github.com/KiCad/kicad-library/pull/705

**Comment by jkriege2** [comment]
I modified all TO-92 to conform to KLC now (added Fab, improved CrtYrd, ...)

JAN

**Comment by jkriege2** [comment]
see #14 for fixes of most of the other packages!

**Comment by SchrodingersGat** [comment]
Hi @jkriege2 this is a great effort. The only suggestion I can make at this stage is to make pin-1 square

**Comment by jkriege2** [comment]
Hi @SchrodingersGat : DONE!

**Comment by SchrodingersGat** [comment]
Fantastic work as always :)

**Pull request merged**
