### PR TITLE
Update TO-220 footprint names

### PR DESCRIPTION
**Pull request by evanshultz**
Based on the discussion at https://github.com/KiCad/TO_SOT_Packages_THT.pretty/issues/26, I've updated all TO-220 package names to be consistent. Here are the changes:
- All footprints start with `TO-220-`
- Added pin number to 3-pin footprints (since current FPfilters ignore pin numbers this should be OK)
- Removed `Multiwatt` and/or `Pentawatt` from footprint names
- Ensured the terms above are present in the description
- Corrected 3D model location/scaling/rotation as needed

This will likely break some 3D models because names changed! Prominently the common 3-pin devices.

### CODE REVIEW

**Comment by jkriege2** [comment]
I would propose to not correct the scaling of 3D models for now, but leave it compatible with the existing models (unless you plan to also post new models). Then please also make PRs that correct all footprint-fields in the kicad-library and (if necessary) the FPFIlters. These PRs should also rename the 3D models. This is a bit more work now, but leaves us with working 3D models. New models (with correct scaling) can then be added in a second step!

**Comment by evanshultz** [comment]
@jkriege2 I understand, but I'd rather try to get it in one go.

My audio.lib update will fix the FPfilters there. How else can I figure out where these footprints are used?

@Shackmeister @hackscribble  I'm not familiar with 3D models. Would you update the TO-220 3D model names and scaling as above, based on the existing models, so that could be done together?

**Comment by evanshultz** [comment]
@Shackmeister @hackscribble Are either of you able to help?

**Comment by Shackmeister** [comment]
@evanshultz Hey Evan, first of all nice work!
regarding the models and scaling: all the ones you have changed the scalings on, are the deprecated wings models. at some point they will need to be remade with Freecad (possibly scripted) but I dont think that time is now (at least I dont have the time). For this reason I would suggest to keep the current scaling, position etc. and only change the name.

**Comment by jkriege2** [comment]
About finding the footprint-uses, I usually use notepad++ (on windows, or any other editor that can search&replace in files). 
2017-10-04 07_47_59-in dateien suchen

Typically you'll need 2-3 different search terms for footprint fields and FPFilters (sometimes I use regexp here too) to fix 95-100% of all linked footprints ... if some are not changed that's fine (we do our best), I would say.

Does it help?

cu
JAN

**Comment by evanshultz** [comment]
3D model rotation/scaling/placement has been reverted.

Are the 3D models at https://github.com/KiCad/kicad-packages3D/tree/master/TO_SOT_Packages_THT.3dshapes? That only has 11- and 5-pin models, which isn't such a burden. But 3-pin is so common I feel there must be models elsewhere.

I located parts that use these footprints in the existing symbol library and submitted a PR to update them at https://github.com/KiCad/kicad-library/pull/1695. Of course, I've not included audio.lib there. Once that PR and this one are merged, I'll update my PR for audio.lib to update footprint names.

For the record, here are the changes grouped by pin count:
- `3`: Add `-3` after `TO-220`
- `5`: Remove `..._Pentawatt_Multiwatt-5...` from footprint name
- `7/9`: Remove `..._Multiwatt-7...` or `..._Multiwatt-9...` from footprint name
- `11/15`: Change `Multiwatt...` to `TO-220...`

**Comment by SchrodingersGat** [comment]
Great, thanks @evanshultz

**Pull request merged**
