### PR TITLE
add new versions of MountfromLS footprints

### PR DESCRIPTION
**Pull request by jkriege2**
this PR complements https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14 with some footprints that were a matter of debate, as they have the packages mounted below the PCB, but the (dashed) silkscreen on the frontside
2017-02-12 13_06_35-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2017-02-12 13_05_25-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb

### CODE REVIEW

**Comment by evanshultz** [comment]
Triggering Travis.

@jkriege2 One part may have an error, and all the rest don't use an env var for the 3D model path.

**Comment by evanshultz** [comment]
@jkriege2 Can you take a look at this PR again?

**Comment by jkriege2** [comment]
Question is whether we want these parts at all ...
@SchrodingersGat @poeschlr @pointhi @CarlPoirier Your thoughts on that?

Best,
JAN

**Comment by evanshultz** [comment]
I dropped a couple Diode_TO-220_Dual_CommonCathode_Horizontal on a board, one on top and one on bottom. To me, the existing footprints already capture everything required.
image

What would have value to me is footprints with the tab up (away from the PCB) and tab down (against the PCB, like you see above). And with various lead preps (leads staggered, in a line, etc.). That would inflate the library with footprints, but they're valid preps for this package and have unique (and quite different) 3D models. IPAK is another package where various preps are possible. Here's an example image I saw online:
image

**Comment by SchrodingersGat** [comment]
@jkriege2 

In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
