### PR TITLE
Fix mirrored TO-18_3Pin footprint

### PR DESCRIPTION
**Pull request by plaes**

### CODE REVIEW

**Comment by plaes** [comment]
3D-model seems to be mirrored too.

**Comment by odurc** [comment]
@plaes according [this](http://www.ti.com/lit/an/snoa033/snoa033.pdf) TI document it's fine. which reference do you have?

**Comment by michal777** [comment]
In the http://www.ti.com/lit/an/snoa033/snoa033.pdf it may be mirrored view.
There are more footprints that may be wrong (TO-12, 18, 43, 72, 3).
http://img.auctiva.com/imgdata/9/8/6/0/1/1/webimg/578257617_o.jpg

**Comment by plaes** [comment]
Yes, these are mirrored.
I currently have a 2N2907A in TO-18 package in my hand and the drawing on page 11 is correct only if you're looking from the pins side.

I also discussed this issue in #kicad channel when I discovered it, and general consensus was that footprint is buggy.

**Comment by BenediktSeidl** [comment]
I've stumbled upon the very same issue. I've just snapped a picture of the transistor (bc177b) and added a drawing of another [datasheet.](http://datasheet.octopart.com/BC107A-Multicomp-datasheet-13708371.pdf) The current footprint is definitive wrong.

to-18-3pin

**Comment by odurc** [comment]
Thank you.

**Pull request merged**
