### PR TITLE
TO12 TO33: pinorder, drillsize and outline

### PR DESCRIPTION
**Pull request by BenediktSeidl**
- changed drill from 1mm to 0.7mm (wire width is max 0.533mm)
- changed pad size from 2mm to 1.8
- corrected pinorder: datasheet shows the transistor from bottom
- smaller tab according to datasheet
- pin 1 is now at (0, 0)
- pin 1 is now at the left (top/middle)

data sheets used as reference
http://www.jedec.org/sites/default/files/docs/archive/to/to-012.pdf
http://www.jedec.org/sites/default/files/docs/archive/to/to-033.pdf
http://pdf.datasheetarchive.com/indexerfiles/Scans-026/ScansUX7104.pdf

dimensions are the mean between minimum and maximum.

the top row shows the package before the edit, the bottom is the new outline. the bottom right shows a overlay of the picture from the data sheet and the new variant (because the tab looks a bit to small, but is according to the data sheet)
to-12

### CODE REVIEW

**Comment by BenediktSeidl** [comment]
- there seems to be no 3pin variant of to-12 and to-33, so perhaps it would be best to remove the _4Pin from the filename?

**Comment by jkriege2** [comment]
Hi!

I just saw your (rather old ;-) PR So first of all: thanks for the contribution! ... Could please still do the following changes:
1. remove the `F.SilkS` from the pads (otherwise theres Silkscreen overlaying the coppr of the pads
2. add a F.FAB.layer with the outline of the device (see e.g. this PR: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/12)

You can check KLC-conformity also with our set of python scripts: https://github.com/KiCad/kicad-library-utils

The output of those scripts for the current version of your PR is:

```
checking module: TO-12_TO-33_4Pin
  Violating Rule 10.3
    Keywords are separated by spaces.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module

```

Best,
JAN

**Comment by jkriege2** [comment]
this is fixed/replaced in this PR: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14

**Comment by jkriege2** [comment]
This is fixed this this PR: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14

best,
JAN

**Pull request closed without merging**
