### PR TITLE
fixed KLC issues of TO-18 footprints + use of new 3D models now

### PR DESCRIPTION
**Pull request by jkriege2**
- use new 3D package now correctly (https://github.com/KiCad/kicad-library/pull/734)
- added CrtYrd
- fixed KLC issues

to183
to183fp

### CODE REVIEW

**Comment by diggit** [comment]
I believe, CrtYd should be around that pin marker too.

**Comment by diggit** [comment]
Also silkscreen should not be hidden under device. Inner circle will never pass.

**Comment by jkriege2** [comment]
Fixed 
to

**Comment by jkriege2** [comment]
@diggit: You already merged the new 3D models (https://github.com/KiCad/kicad-library/pull/734) ... so now we still need the footprints ... are these OK, or is anything missing?

Best,
JAN

**Comment by jkriege2** [comment]
this is now part of https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14

**Comment by diggit** [comment]
Sorry @jkriege2, I have several rough weeks in school. Sb else should take a look on PRs I replied. No spare time for kicad for now.

**Pull request closed without merging**
