### PR TITLE
TO18 2pin: correct pin order

### PR DESCRIPTION
**Pull request by BenediktSeidl**
- changed pin 1 to (0, 0)

pin order according to datasheet [Si PIN photodiode S5821 series](https://www.hamamatsu.com/resources/pdf/ssd/s5821_series_kpin1010e.pdf)

at the top the old to18 packages, below the new 2 pin variants with the pinout from the data sheet
to-18-2pin

### CODE REVIEW

**Comment by BenediktSeidl** [comment]
I've also created [pull request #233 at kicad-library](https://github.com/KiCad/kicad-library/pull/392) to update the 3d model.

**Comment by jkriege2** [comment]
Hi!

a more complete overhaul is here: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/12

best,
JAN

**Comment by jkriege2** [comment]
this and more is fixed in https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14

**Comment by jkriege2** [comment]
This is fixed this this PR: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14

best,
JAN

**Pull request closed without merging**
