### PR TITLE
reworked round & rectangular TO-packages, added missing

### PR DESCRIPTION
**Pull request by jkriege2**
reworked rectangular and round TO-XYZ packages:
- added Fab-layer for footprints
- added several missing symbols
- created round symbols with and without window
- using common/clean naming convention
- added some 3D packages in: https://github.com/KiCad/kicad-library/pull/797
- corrected several wrong packages (especially round TO-packages)
- see for scripts: https://github.com/pointhi/kicad-footprint-generator/pull/14
- see #11 for fixes for TO-92

tosot_test-brd

tosot_test

### CODE REVIEW

**Comment by jonasstein** [comment]
Where did you take the radius of shaded inner circle of the TO-xx housings from? Some are to the center of the holes, some are larger. Any way thank you very much for pushing the missing TO-xx libraries forward. I like your suggestion with sqare pads for No. 1 pads very much. Are you sure about the diameter of the drill holes? Some look very large to me in your attached picture. Best, JS.

**Comment by jkriege2** [comment]
Hi!

most of the window radii are from diverse datasheets ... They sometimes vary, so some are just estimates.

Which holes do you think are too large?

Best,
JAN

**Comment by jonasstein** [comment]
TO-220 for example has hardly any Cu left at the thin part of the square pad.
please check TO-262 too. Best, JS

**Comment by jkriege2** [comment]
Hi!

OK, TO-262 I'll have to change for sure ... for the TO-220 I'm not so sure ... Here the copper is roughly as in the old parts (see above the new ones!) ... One could maybe elongate the pads, as in the old parts ... What do you think?

cu
JAN

**Comment by jkriege2** [comment]
Hi!

I changed the size of the TO-262 copper ring:
to-262
 What do you think?
JAN

**Comment by jkriege2** [comment]
fixed conflicts!

**Comment by jkriege2** [comment]
Please review?

**Comment by SchrodingersGat** [comment]
Ok, I'll have a go.. What a PR!

## Naming Convention
I think the file naming can be cleaned up here.

### Remove "Pin"

Look at the way that parts are named in https://github.com/KiCad/TO_SOT_Packages_SMD.pretty (e.g. SOT-23-5, SC-70-5)

I would suggest removing the "pin" text from many part names, they can be simplified to (e.g.):

`TO-33_4Pin` -> `TO-33-4`

### Move Suffix Position

Many parts have suffix e.g. "Window" - I would move this AFTER the pin number, such that parts are automatically ordered by pin count. Example:

`TO-33_Window_4Pin` -> `TO-33-4_Window`
`TO-5_PD5.08_8Pin` -> `TO-5-8_PD5.08`

## _MountFromLS

I am not sure I understand the rationale behind these parts - can you not just flip the parts to the other side of the board? What is the use-case of the MountFromLS variants?

## TO220-5/7/9

The -5/-7/-9 variants of the TO220 have some strange additions to the part name (Pentawatt, Multiwatt). Is this desired? If so, what is the purpose?

Great work in general. Let's deal with these and we can move forward.

Cheers, Oliver

**Comment by jkriege2** [comment]
Hi!

I'll give some short answers now and more thorough answers over the weekend (I'm not at home right now ;-)

About naming: can be done ... I was pondering with this a bit myself. My idea was this: We have certain classes of packages (e.g. I know, I need a TO-33 with a window, or a TO-5 where the pins are on a circle with dimaetr 5.08mm). Then in a secons step I select the package with the correct pin count ... 
But then it is maybe really better to have it   as it is done in the other libs (for consistency) ... So I'll change that ;-)

THe mounfromLS was something I wanted to have removed, but kept due to some discussions with another contributor. The idea is that these are packages mounted on the bottom, but with the metal not towards the PCB, but also to the bottom, so you can put them on a heatsink that is parallel to the PCB (e.g. here: https://www.jlmaudio.com/shop/images/cache/KRAFTWERK_on_heatsink_640.580.JPG

About the TO-220-5/7/9 They are typically know by both names, e.g. TO-220-5 and Pentawatt, so having both names in the filename allows to match the footprints by searches for either TO-220-5 or Pentawatt. Also I kind of tried to stick to the convention set by existing footprints, as e.g. `Pentawatt_Neutral_Staggered_Verical_TO220-5-T05D`´, just ensuring that the TO-XYZ-naming is in front for all (consistency again). The same I've done by the way for the IPAKs (TO-251) and I²PAKs (TO-262). Any idea on how to handle this in a better way?

Best,
JAN

**Comment by jkriege2** [comment]
OK, renamed as requested
https://github.com/KiCad/kicad-library/pull/797 has been updated too!

OK with you?
Best,
JAN

**Comment by SchrodingersGat** [comment]
Isn't the "mountFromLS" functionally equivalent to the "Reversed" packages (as the heatsink when bent will be facing away from the PCB)?

**Comment by jkriege2** [comment]
Hi!

the difference is that the part is on the back, but the silkscreen is still on the top ... I create these, because they were there originally and due to a discussion with Bernd Wiebus on the kicad-lib-commiters-list:
https://lists.launchpad.net/kicad-lib-committers/msg00450.html

Should we keep it, or remove it? I would rather keep it ... you can still ignore it of you don't want it!

Best JAN

PS: For illustration:
2017-01-12 16_30_10-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb
2017-01-12 16_30_37-3d viewer
2017-01-12 16_31_04-3d viewer
2017-01-12 16_31_32-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb

**Comment by pointhi** [comment]
Looking at the images provided, you need to redo the silkscreen layer. There is no strong logical connections between dotted lines and hidden parts as well as for normal lines and visible parts.

**Comment by jkriege2** [comment]
Then how would you do it? 
For these parts (and how they were before) solid lines represent edges that are near the PCB and dotted lines represent edges that are off the PCB or under the PCB ... not really nic, I know but ... Any idea how to do it? If we come to some idea it will not be too hard to imeplement it, as this ia all scripted!

best,
JAN

**Comment by jkriege2** [comment]
@pointhi @SchrodingersGat @ashtonchase @reportingsjr  any input on this?

**Comment by jkriege2** [comment]
What do you think of this change:
2017-02-12 13_05_25-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2017-02-12 13_06_35-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb

Now large dashes are used for the reversed on-front-mounted and the mounted-from-LS has the plastic-part-separation shown.

So now small dashes are always mounted from below (should we also have a text for that, as in the old footprints) and large dashes are reversed on front of PCB.

Best,
JAN

**Comment by SchrodingersGat** [comment]
I still do not see the need for having a separate footprint where the transistor is on one side and the silk-screen is on the other? Can you provide a specific use-case for this? I read the link to the discussion with Wiebus above but remain unconvinced.

Another point regarding naming convention:

e.g. for the TO218 / SOT93 parts: I think that the ordering of naming should be as thus:
```
TO218_SOT93_Horizontal
TO218-2_SOT93_Horizontal_Reversed
```

The current naming of these parts is confusing to parse.

I can't see any other issues at this point - it is a great addition you are making here.

**Comment by jkriege2** [comment]
Hi1

I will do the renames. Also I asked @wiebus via mail to contribute to this discussion and make his point here. I'm thinking about splitting this PR, so we can discuss all the `_MountedFromLS`-footprints in a second PR, but that leaves the question whether we should keep the existing `_MountedFromLS`-footprints (i.e. not delete, which is part of this PR) until the new PR is discussed (but then we have an inconsistent state in the trunk, as some footprints are old and some are new), or live with an intermediate state where some parts are simply not available.

best,
JAN

**Comment by jkriege2** [comment]
- OK, renames are done.
- I removed all `_MountFromLS` and posted them separately here: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/16
- please don't forget to also merge the 3D models: https://github.com/KiCad/kicad-library/pull/797

Can be merged now?

**Comment by SchrodingersGat** [comment]
Yes, thanks for the hard work Jan :)

We shall have to work out what to do with #16

**Pull request merged**
