### PR TITLE
Adding TO-46-3_Lens footprint

### PR DESCRIPTION
**Pull request by yhlien**
Adding a TO-46-3 footprint equipped with a 1.5 mm diameter ball lens.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

Please also change all the texts and 3D model names inside the `.kicad_mod`!

Best,
JAN

**Comment by jkriege2** [comment]
@yhline ... you can do these changes also bei a simple search&replace with any text-editor (usually faster than in KiCAD)! ... just a hint ;-)

JAN

**Comment by yhlien** [comment]
@jkriege2 Sorry I commit the changes too quickly. I will modify the text later. Please ignore the committed changes temporarily.

**Comment by jkriege2** [comment]
Hi!

I had a closer look at your PR ... The way I see it, these are merely copies of the existing packages,, with the only modification of different window sizes. Correct?

So I'm thinking whether we really need these ... or whether the existing generic footprints would be sufficient (when designing them I more or less estimated the size of the windows/lenses). The drawback would be that the F.Fab layer-sketches are less accurate and that we may not have specific 3D models. Correct?

@SchrodingersGat @pointhi @poeschlr What do you think?

Best,
JAN

**Comment by poeschlr** [comment]
I'm not really sure if we need different 3d models. (Other than for eye candy)
As long as the outer dimensions of the packages are equal i don't see any reason for including them.

**Comment by yhlien** [comment]
Hi
Sorry for getting  back late as I was away in these days.

For the footprints, yes. Most of the parts I added are slightly modified existing footprints to represent the different sizes of the optical components (windwo, lens).

On the other way, I also have some revised components which also include new 3D models. Would you please advise what you prefer after checking the newly revised ones?

**Comment by jkriege2** [comment]
Hi!

I'm thinking that it would be better to keep it simple and NOT have variants  for each lens/window diameter ... For  users of the lib it is otherwise very hard to see which footprint to use.

If you absolutely want the special 3D models for teh Thorlabs diodes, I would propose to rename the footprints to someting like `Thorlabs_FDS100`, `Thorlabs_FDS010`, ...
If you do that, please also ensure that the 3D models have the exact same name as the footprint and add `` to the 3D paths (KLC 10.4 violation reported by Travis!).

Abou the 3D models for this PR (from https://github.com/KiCad/kicad-library/pull/1064): Where did you get them from? If you made them yourself, please ensure to submit the following (bit complex at the moment, but the workflow is slowly developing):
1. Sources (e.g. FreeCAD project-files FCStd) should go to https://github.com/KiCad/packages3D-source
2. Output (VRML/WRL+STEP-files) should go to two places: 
** https://github.com/KiCad/kicad-library/tree/master/modules/packages3d as that's the place where KiCAD currently searches for the 3D models
** https://github.com/KiCad/packages3D as that is where the models will move to in future
3. WINGS is no longer used. Currently VRML is the format of choice for KiCAD, but I think future versions will be able to read STEP. Also STEP is required for good export to mechanical 3D-CAD

If you downloaded the 3D models somewhere: How are they licensed? Does their license allow uploading here (Most commercial 3D models may not be shared and will not be accepted here)?

Best,
JAN

**Comment by SchrodingersGat** [comment]
@poeschlr @jkriege2 agreed, variants based simply on window size present a lot of clutter without much (any?) benefit to most users.

**Comment by yhlien** [comment]
Hi Jan,

The 3D models were downloaded from Thorlabs in STEP format and I converted them from STEP into VRML via FreeCad.

BTW, should I include the STEP files as well?

So far I do not notice any terms on Thorlabs' website but I am certainly happy to check with them to see whether there is any copyright issue for me to do so.

**Comment by jkriege2** [comment]
Yes please ask Thorlabs! Usually the 3D models are provided for private use and you may not redistribute them ... When asking them, plese refer to this website and tell them that the KiCAD lib is licensed under the LGPL (https://github.com/KiCad/kicad-library/blob/master/COPYRIGHT.txt) ...

If they agree on posting the models here under those license terms, please state that here (Copy of email?) ...

If they don't agree, we unfortunately cannot accept the 3D models. If we keep the footprints though, leave in the 3D model links, then you can provide the models locally on your computer under the correct name+location and KiCAD will find them for you ... just not out-of-the-box.

Best,
JAN

Best,
JAN

**Comment by yhlien** [comment]
Hi,

I am thinking whether I should add a prefix like TO-18 in front of the customised footprints, e.g., TO-18-3_Thorlabs_FDS100? Otherwise, they look bit odd to stay in TO_SOT_Packages_THT.pretty...

**Comment by jkriege2** [comment]
No, please leave it as is. If you want the TO inside, use the form `Thorlabs_FDS100_TO-18-3` usually for company-specific packages, you should simply habe `MANUFACTURER_PACKAGENAME`.

Best,
JAN

**Comment by yhlien** [comment]
In that case, I will just leave it as it is now. I did put the TO package type in the doc field and hope it is informative.

**Comment by jkriege2** [comment]
Hi!

Please have ONE model per package only, i.e.  Thorlabs_FDS025 and  Thorlabs_FGA01 seem the same, so remove one and reference the remaining one from both symbols.

Also please have a look at the text you put in. You say the window is e.g. 15mm on the two footprints mentioned above, but that's larger than the package ... did you mean 1.5mm?

@poeschlr @SchrodingersGat @pointhi Should we accept these variants as manufacturer variants? ... I'm not sure ... If one needs the actual diodes in the 3D mdoel, I can see that this would be handy (e.g. to position the diodes in a housing where they should exactly be ... in the end these are photodiodes). Please vote, so we see where this PR will go to ...

cu
JAN

**Comment by evanshultz** [comment]
@jkriege2 Is there still work to be done after the last update by @yhlien?

@poeschlr @SchrodingersGat @pointhi Can someone read and help to answer the question raised by @jkriege2 above?

**Comment by evanshultz** [comment]
Anybody???

**Comment by poeschlr** [comment]
@jkriege2 wrote:
>Should we accept these variants as manufacturer variants? ... I'm not sure ... If one needs the actual diodes in the 3D mdoel, I can see that this would be handy (e.g. to position the diodes in a housing where they should exactly be ... in the end these are photodiodes). Please vote, so we see where this PR will go to ...

I don't see a problem adding them as manufacturer footprint variants.
Even if only the 3d model differs. Especially if there is a usecase (other than eycandy) where having a precise model might be vital. For optical sensors this is the case. (The designer of the housing might need to know where exactly the lense is and how big it is.)

@evanshultz i did not really follow the conversation i think jan needs to take another look if his requests have been fulfilled.

**Comment by SchrodingersGat** [comment]
@yhlien 

In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
