### PR TITLE
fix all KLC2.0 issues

### PR DESCRIPTION
**Pull request by jkriege2**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
It looks like the --fix option has failed here. A non-named pin should be called `""` but here it is called `None`

**Comment by SchrodingersGat** [comment]
Actually that line wasn't changed. Why do these footprints have pads labelled "None"?

**Comment by jkriege2** [comment]
that looks like a glitch in my scripts for these ... I fixed it to 0, so it can - in theory - be connected (those are the mounting holes for TO-220-like packages)

**Comment by SchrodingersGat** [comment]
Thanks for fixing! checks out with new KLC :)

**Pull request merged**
