### PR TITLE
Move Allegro CB packages

### PR DESCRIPTION
**Pull request by evanshultz**
As discussed at https://github.com/KiCad/PFF_PSF_PSS_Leadforms.pretty/issues/2, moving these footprints here so the old lib can be deprecated. Since these footprints were rather old, I did some much-needed updating too. Changes:
- Updated tags to remove commas
- Updated descriptions
- Use env var in 3D model path
- Added ref des on F.Fab
- Fixed 3D model scale to 1 1 1
- Removed silk lines that approximated text
- PFF/PSF: Corrected pads to 0.8mm drill with 1.5mm annular ring
- PFF/PSF: Made pad 1 square
- PFF/PSF: Set 2.9mm between row of pads and body
- PFF/PSF: Moved origin to pad 1
- Corrected F.Fab lines or added if not present
- Moved silk lines to fit and made all 0.12mm wide
- Added courtyard
- Renamed fooprints to `Allegro_CB_Pxx`
- PSF: Centered SMT pads on leads horizontally
- PSF/PSS: Made the board cutout rectangular and 0.5mm around body nominal size

Notes:
1. The PFF pads 4 & 5 are ugly but I'd like to wait to update until v5 when polygon shapes are available.
1. All footprints are in TO_SOT_Housings_THT so they're grouped together even though PSS is really SMD.
1. Retained PSS pad height for pins 1-3 that is shorter than uncut pin length; should the pads be taller?

Image:
image

@SchrodingersGat Since we discussed the above item, do you mind to take a look?

### CODE REVIEW

**Comment by evanshultz** [comment]
Hmm... I set Notepad++ to Unix-style line endings and I'm getting issues now. Never seen this before with any other push. Any tips?

**Comment by evanshultz** [comment]
Weird. Uploaded the files again and all is well.

**Comment by evanshultz** [comment]
@SchrodingersGat Would you be able to take a look?

**Comment by evanshultz** [comment]
@SchrodingersGat Can you take a look?

**Comment by evanshultz** [comment]
@SchrodingersGat ?

**Comment by evanshultz** [comment]
@SchrodingersGat Oliver, are you able to look at this PR?

**Comment by SchrodingersGat** [comment]
Hi Evan sorry that it has taken me so long to look at this.

I like the footprints in general, the PFF version I have some thoughts on.

Using the cutout layer for the rounded holes will mean that the sides of the hole are not plated (unless this is specified to the board house).

I have actually used this footprint on a production board. For this I specified an oval hole with oval drill.

image

As long as the fab house can do plated slots (which I think are necessary for this footprint anyway!) then this should be fine. 

I do actually have a version with the extra drills around the perimeter of the main pad, but I can't find it :| 

In any case, I like the addition of the extra drills. You should make them all circular with a diameter of 1mm. Also the datasheet says hole diameters should be 0.5mm

Thus, required hole changes:

1. Make them normal holes, not lines
1. Oval drill on an oval pad
1. Make extra drills 0.5mm with 1.0mm pad

Here is a side-by-side with my footprint. It's not KLC (from a very old design) but it has been verified in use (100A!)

image

Note the realignment of the `F.Fab` text for the footprint on the right. I think the text should be arranged thusly for all three footprints.

And a 3D model 

image

The through holes for the PFF are the only thing holding this PR back :)

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks for taking a look!

I left the PFF pins 4 and 5 alone because I was waiting for polygon pads, as mentioned above. We won't be able to slice off the edge of the pads, but since the resistance between those pads is to low there won't be substantial voltage breakdown concerns so manufacturing is my only concern. The pad size should be (10,6) from the datasheet, but you used (8.5,5). I selected (9,6) pads since that gives ~1mm gap between pads per the datasheet but is otherwise as large as possible. I made a note in the description to point out the reduced pad size.

Next, I calculated and properly placed all the vias in the big pads. The drill size was changed to match the datasheet and I made the annular rings as small as possible since they live inside the big pads.

F.Fab text is moved as you mentioned, then used a pair of F.Fab lines to represent 0.51mm wide leads.

When I was poking around in here, I realized the pads show 1.91mm spacing while the pins are 1.9mm. I left it alone at 1.91mm since that matches the recommended PCB layout, but it's odd that they're different.

A few notes:
1. PSF/PSS: Silk is placed inside the board cutout, but I think that's OK.
1. PSS: The pads didn't fit the full 11mm lead length and the datasheet has no recommended PCB layout for this package. Not knowing if trimming the leads is common, nor seeing any PSS results in a Google image search, I enlarged the pads for pins 1-3.

These footprints were in pretty poor shape before, but hopefully they're quite usable now!

Image:
image

Anything else?

**Comment by evanshultz** [comment]
I just uploaded new files which have Unix line endings. Notepad++ said they already were, but I went to Windows and back to Unix and now all is well. Curse you, Notepadd++!

I also noticed that there are no pin 1 marks on F.Fab. Is this OK on all footprints? Maybe only the PSS needs it? Ideas on the best way to do this? It could be a bevel on the body outline near pad 1?

**Comment by SchrodingersGat** [comment]
Good point regarding pin-1 indication on F.Fab. I'd suggest a small triangle between the body and pad-1. Looks like there's enough space on each footprint.

**Comment by evanshultz** [comment]
Like this?
image

**Comment by SchrodingersGat** [comment]
Yeah that looks good to me

**Comment by evanshultz** [comment]
@SchrodingersGat Added pin 1 mark. Ready for merge!

**Comment by SchrodingersGat** [comment]
Great! Thanks for your work

**Pull request merged**
